language: node_js
node_js:
  - 10
cache:
  yarn: true
  directories:
    - node_modules
stages:
  - name: test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: test
      script: yarn test
    - stage: deploy
      before_install:
        - sudo apt-get install -y libsecret-1-dev
      script:
        - graph auth https://api.thegraph.com/deploy/ $THEGRAPH_TOKEN && yarn deploy
env:
  - SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
